-- Таблица пользователей
CREATE TABLE IF NOT EXISTS "user" (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      login VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    birthday DATE NOT NULL
    );

-- Таблица рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa_rating (
                                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(255) UNIQUE NOT NULL
    );

-- Таблица жанров
CREATE TABLE IF NOT EXISTS genre (
                                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) UNIQUE NOT NULL
    );

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS film (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration_in_ms BIGINT,
    mpa_rating_id INT NOT NULL,
    CONSTRAINT fk_film_mpa FOREIGN KEY (mpa_rating_id) REFERENCES mpa_rating (id) ON DELETE RESTRICT
    );

-- Таблица связей фильмов и жанров
CREATE TABLE IF NOT EXISTS film_genre (
                                          film_id BIGINT,
                                          genre_id INT,
                                          PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_fg_film FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    CONSTRAINT fk_fg_genre FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE RESTRICT
    );

-- Таблица друзей
CREATE TABLE IF NOT EXISTS friend (
                                      user_id BIGINT,
                                      friend_user_id BIGINT,
                                      is_confirmed BOOLEAN DEFAULT FALSE,
                                      PRIMARY KEY (user_id, friend_user_id),
    CONSTRAINT fk_friend_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
    CONSTRAINT fk_friend_target FOREIGN KEY (friend_user_id) REFERENCES "user" (id) ON DELETE CASCADE
    );

-- Таблица лайков
CREATE TABLE IF NOT EXISTS film_like (
                                         film_id BIGINT,
                                         user_id BIGINT,
                                         PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_like_film FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
    );
