-- 1. Таблица пользователей
CREATE TABLE IF NOT EXISTS user_app (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(255) NOT NULL UNIQUE,
    name varchar(255),
    email varchar(255) NOT NULL UNIQUE,
    birthday date NOT NULL
    );

-- 2. Таблица рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa_rating (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
    );
-- Устанавливает следующее значение автоинкремента на 6
ALTER TABLE mpa_rating ALTER COLUMN id RESTART WITH 6;
-- 3. Таблица жанров
CREATE TABLE IF NOT EXISTS genre (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
    );

-- 4. Таблица фильмов
CREATE TABLE IF NOT EXISTS film (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(200),
    release_date date NOT NULL,
    duration_in_ms bigint,
    mpa_rating_id int NOT NULL REFERENCES mpa_rating (id)
    );

-- 5. Таблица друзей
CREATE TABLE IF NOT EXISTS friend (
    user_id bigint REFERENCES user_app (id) ON DELETE CASCADE,
    friend_user_id bigint REFERENCES user_app (id) ON DELETE CASCADE,
    is_confirmed boolean DEFAULT false,
    PRIMARY KEY (user_id, friend_user_id)
    );

-- 6. Таблица жанров фильма
CREATE TABLE IF NOT EXISTS film_genre (
    film_id bigint REFERENCES film (id) ON DELETE CASCADE,
    genre_id int REFERENCES genre (id),
    PRIMARY KEY (film_id, genre_id)
    );

-- 7. Таблица лайков
CREATE TABLE IF NOT EXISTS film_like (
    film_id bigint REFERENCES film (id) ON DELETE CASCADE,
    user_id bigint REFERENCES user_app (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );
